export default {
  "accesskeys": "accesskey attribute value should be unique",
  "area-alt": "Active <area> elements must have alternative text",
  "aria-allowed-attr": "Elements must only use supported ARIA attributes",
  "aria-allowed-role": "ARIA role should be appropriate for the element",
  "aria-braille-equivalent": "aria-braille attributes must have a non-braille equivalent",
  "aria-command-name": "ARIA commands must have an accessible name",
  "aria-conditional-attr": "ARIA attributes must be used as specified for the element's role",
  "aria-deprecated-role": "Deprecated ARIA roles must not be used",
  "aria-dialog-name": "ARIA dialog and alertdialog nodes should have an accessible name",
  "aria-hidden-body": "aria-hidden=\"true\" must not be present on the document body",
  "aria-hidden-focus": "ARIA hidden element must not be focusable or contain focusable elements",
  "aria-input-field-name": "ARIA input fields must have an accessible name",
  "aria-meter-name": "ARIA meter nodes must have an accessible name",
  "aria-progressbar-name": "ARIA progressbar nodes must have an accessible name",
  "aria-prohibited-attr": "Elements must only use permitted ARIA attributes",
  "aria-required-attr": "Required ARIA attributes must be provided",
  "aria-required-children": "Certain ARIA roles must contain particular children",
  "aria-required-parent": "Certain ARIA roles must be contained by particular parents",
  "aria-roles": "ARIA roles used must conform to valid values",
  "aria-text": "\"role=text\" should have no focusable descendants",
  "aria-toggle-field-name": "ARIA toggle fields must have an accessible name",
  "aria-tooltip-name": "ARIA tooltip nodes must have an accessible name",
  "aria-treeitem-name": "ARIA treeitem nodes should have an accessible name",
  "aria-valid-attr": "ARIA attributes must conform to valid names",
  "aria-valid-attr-value": "ARIA attributes must conform to valid values",
  "autocomplete-valid": "autocomplete attribute must be used correctly",
  "avoid-inline-spacing": "Inline text spacing must be adjustable with custom stylesheets",
  "bootup-time": "Reduce JavaScript execution time",
  "button-name": "Buttons must have discernible text",
  "bypass": "Page must have means to bypass repeated blocks",
  "color-contrast": "Elements must meet minimum color contrast ratio thresholds",
  "color-contrast-enhanced": "Elements must meet enhanced color contrast ratio thresholds",
  "definition-list": "<dl> elements must only directly contain properly-ordered <dt> and <dd> groups, <script>, <template> or <div> elements",
  "dlitem": "<dt> and <dd> elements must be contained by a <dl>",
  "document-title": "Documents must have <title> element to aid in navigation",
  "duplicate-id-aria": "IDs used in ARIA and labels must be unique",
  "empty-heading": "Headings should not be empty",
  "empty-table-header": "Table header text should not be empty",
  "form-field-multiple-labels": "Form field must not have multiple label elements",
  "frame-focusable-content": "Frames with focusable content must not have tabindex=-1",
  "frame-tested": "Frames should be tested with axe-core",
  "frame-title": "Frames must have an accessible name",
  "frame-title-unique": "Frames must have a unique title attribute",
  "heading-order": "Heading levels should only increase by one",
  "html-has-lang": "<html> element must have a lang attribute",
  "html-lang-valid": "<html> element must have a valid value for the lang attribute",
  "html-xml-lang-mismatch": "HTML elements with lang and xml:lang must have the same base language",
  "identical-links-same-purpose": "Links with the same name must have a similar purpose",
  "image-alt": "Images must have alternative text",
  "image-redundant-alt": "Alternative text of images should not be repeated as text",
  "input-button-name": "Input buttons must have discernible text",
  "input-image-alt": "Image buttons must have alternative text",
  "label": "Form elements must have labels",
  "label-title-only": "Form elements should have a visible label",
  "landmark-banner-is-top-level": "Banner landmark should not be contained in another landmark",
  "landmark-complementary-is-top-level": "Aside should not be contained in another landmark",
  "landmark-contentinfo-is-top-level": "Contentinfo landmark should not be contained in another landmark",
  "landmark-main-is-top-level": "Main landmark should not be contained in another landmark",
  "landmark-no-duplicate-banner": "Document should not have more than one banner landmark",
  "landmark-no-duplicate-contentinfo": "Document should not have more than one contentinfo landmark",
  "landmark-no-duplicate-main": "Document should not have more than one main landmark",
  "landmark-one-main": "Document should have one main landmark",
  "landmark-unique": "Landmarks should have a unique role or role/label/title (i.e. accessible name) combination",
  "link-in-text-block": "Links must be distinguishable without relying on color",
  "link-name": "Links must have discernible text",
  "list": "<ul> and <ol> must only directly contain <li>, <script> or <template> elements",
  "listitem": "<li> elements must be contained in a <ul> or <ol>",
  "marquee": "<marquee> elements are deprecated and must not be used",
  "meta-refresh": "Delayed refresh under 20 hours must not be used",
  "meta-refresh-no-exceptions": "Delayed refresh must not be used",
  "meta-viewport": "Zooming and scaling must not be disabled",
  "meta-viewport-large": "Users should be able to zoom and scale the text up to 500%",
  "nested-interactive": "Interactive controls must not be nested",
  "no-autoplay-audio": "<video> or <audio> elements must not play automatically",
  "object-alt": "<object> elements must have alternative text",
  "page-has-heading-one": "Page should contain a level-one heading",
  "presentation-role-conflict": "Elements marked as presentational should be consistently ignored",
  "region": "All page content should be contained by landmarks",
  "role-img-alt": "[role=\"img\"] elements must have alternative text",
  "scope-attr-valid": "scope attribute should be used correctly",
  "scrollable-region-focusable": "Scrollable region must have keyboard access",
  "select-name": "Select element must have an accessible name",
  "server-side-image-map": "Server-side image maps must not be used",
  "skip-link": "The skip-link target should exist and be focusable",
  "summary-name": "Summary elements must have discernible text",
  "tabindex": "Elements should not have tabindex greater than zero",
  "table-cell-headers-attr": "Table cell headers attributes must refer to other <th> elements in the same table",
  "table-duplicate-name": "Tables should not have the same summary and caption",
  "target-size": "All touch targets must be 24px large, or leave sufficient space",
  "th-has-data-cells": "Table headers in a data table must refer to data cells",
  "valid-lang": "lang attribute must have a valid value",
  "video-caption": "<video> elements must have captions"
}